### PR TITLE
feat: Add French locale

### PR DESCRIPTION
**Pull request by DenB10**
New try

### CODE REVIEW

**Comment by beltrachi** [comment]
Hi @DenB10 !

this new PR did not fix the commit message issue, sorry.

To speed things up I've created another pull request with your translations: https://github.com/beltrachi/automatic_dictionary/pull/278 in case you want to take a look.
I also fixed the commit message, reviewed the non-breaking spaces (I've been investigating a bit lately, first time I find out real usage of this.).

Also I'd like to add you to the README as contributor, if that's fine for you. Its just recognition of your contribution :heart: 

If its OK for you I'll merge my Pull request and close this.

**Comment by DenB10** [comment]
Everything is OK for me.
Thanks for your fix, sorry for my inexperience.

**Comment by beltrachi** [comment]
Hi @DenB10 !

Soon a new version will be available with French localization. I'm waiting for Thunderbird team to approve it. Thank you for your contribution <3

I'd like to localize the description of the addon, and came up with this using AI:
> Se souvient de la langue que vous utilisez avec une personne ou un groupe de personnes, et change automatiquement la langue du correcteur orthographique pour vous la prochaine fois. Vous n'avez plus besoin de le faire manuellement. Il s'en souvient et le change pour vous.

Could you check if this is correct? 

It's a translation from this:
> Remembers the language you use with a person or group of people, and switches the spellchecker language automatically for you next time. You do not have to do it manually any more. It remembers and switches it for you."

**Comment by DenB10** [comment]
Good translator 😉Juste a small fix: the last sentence is useless.Le 7 juin 2024 17:42, Jordi Beltran ***@***.***> a écrit :
Hi @DenB10 !
Soon a new version will be available with French localization. I'm waiting for Thunderbird team to approve it. Thank you for your contribution <3
I'd like to localize the description of the addon, and came up with this using AI:

Se souvient de la langue que vous utilisez avec une personne ou un groupe de personnes, et change automatiquement la langue du correcteur orthographique pour vous la prochaine fois. Vous n'avez plus besoin de le faire manuellement. Il s'en souvient et le change pour vous.

Could you check if this is correct?
It's a translation from this:

Remembers the language you use with a person or group of people, and switches the spellchecker language automatically for you next time. You do not have to do it manually any more. It remembers and switches it for you."

**Comment by beltrachi** [comment]
Removed last sentence then. Thanks!

**Pull request closed without merging**
