### PR TITLE
first step toward 102

### PR DESCRIPTION
**Pull request by jobisoft**
This is the first step. It removes the spellchecking experiments (which no longer work due to core changes) and replaces their usage by the new APIs. The getter is throwing away all but the first, to not have to touch the other logic.

The `canSpellCheck` Experiment has no equivalent, but you did already return true for TB > 89. This version of the add-on will only work in TB102 or greater, so the `canSpellCheck` Experiment would always return true as well. So I removed it. There are still two usages in the tests, which I did not understand completely and therefore did not touch them.

### CODE REVIEW

**Review by beltrachi — COMMENTED** [review]
Hi,

first of all, thanks for investing time on this.

I like your approach of "just use the first language". It will make the transition a lot easier and will allow users to still use it in a basic way.

As I mention in separate comments there are some tests that should not be removed but adapted.

Did you try to run the tests? https://github.com/beltrachi/automatic_dictionary#development They are failing with your PR. I'll investigate how to make github run them for fork's PRs.

I've been busy lately but I think I can come up with a version this week, based on your PR, that works on TB 102. Is that OK for you?

**Comment by jobisoft** [comment]
> I've been busy lately but I think I can come up with a version this week, based on your PR, that works on TB 102. Is that OK for you?

Yes, of course, happy to help.

In my PR I removed `browser.compose_ext.getCurrentLanguage` and `browser.compose_ext.setSpellCheckerLanguage`, so I thought I can remove the tests as well.

**Comment by beltrachi** [comment]
I've merged to master the development using your commits and other fixes. I'll release a new version now.

Thanks John!

**Comment by beltrachi** [comment]
@jobisoft by the way, in the event of dictionaries changed I had to do some trick to ignore the event when reply window is loaded. 
All described here https://github.com/beltrachi/automatic_dictionary/commit/c07cc97849670b5a022dacf58898eb3d7793dc01

Do you know if the window emits any event when it's loading? Maybe I could ignore any "active dictionaries changed" event until window is fully loaded?
Or maybe the event could be tainted with some flag when its user interaction (changing dictionaries) to distinguish that from window initialization?

**Pull request closed without merging**
